filter_length:      16384

float_bits:         32

overflow_warnings:  true
allow_poll_mode:    false
monitor_rate:       true
powersave:          -80
lock_memory:        true
show_progress:      false
