#!/bin/bash

# This script starts or stops the necessary jack to PA ports and the PA loopack,
# in order to use a BT loudspeaker under PA as a pre.di.c input monitor,
# under a Desktop installation of pre.di.c

# Remember you need to declare the jack to PA ports 'pulse_source' inside
# the 'jack_monitors:' section under <config.yml>

###############################################################
# BT loudspaker address configured as found by
#       ~/pre.di.c/clients/PA_BT_lspk_monitor/PA_BT_1st_device.py
# or alternatively you can give it it from command line.
###############################################################

BTaddr=$(~/pre.di.c/clients/PA_BT_lspk_monitor/PA_BT_1st_device.py)

if [ $2 ]; then
  BTaddr=$2
fi
BTaddr=${BTaddr//:/_}
BTsink="bluez_sink."$BTaddr".a2dp_sink"

# If called with 'stop', arakiri
if [[ $1 == stop ]];then
    pkill -f BT_lspk_monitor_watchdog
    exit 0
fi

if [[ $1 != start ]];then
    echo  "usage: BT_lspk_monitor_watchdog   start [BT_address] | stop" 
    exit 0
fi

# Watchdog that checks if the BT loudspeaker is available under the PA user session:

started=no

while true; do

    tmp=$(pactl list sinks short | grep $BTsink)

    if [[ $tmp ]]; then

        if [[ $started == no ]]; then
            # Starting
            echo '(i) BT loudspeaker is available under Pulseaudio, '
            echo '    connecting as a pre.di.c input monitor'
            ~/pre.di.c/init/pulseaudio-jack-source+loopback start $BTaddr &
            sleep 3
            # Reconnecting the current input in order to reach the new monitor ports
            input=$(grep input ~/pre.di.c/config/state.yml | cut -f2 -d' ')
            control input $input

            started=yes
        fi

    else
        if [[ $started == yes ]]; then
            # Stopping
            echo '(i) BT loudspeaker not available under Pulseaudio'
            ~/pre.di.c/init/pulseaudio-jack-source+loopback stop

            started=no
        fi
    fi

    sleep 5

done

