#!/usr/bin/env python3
"""
    Starts / stops ebumeter GUI interface as a source monitor under pre.di.c
    use:   ebumeter    start | stop
"""

import sys
from subprocess import Popen
from ruamel.yaml import YAML

import basepaths as bp

def start():
    
    def check_config():
        """ Appends ebumeter in jack_monitors under config.yml, if necessary.
        """
        yaml = YAML()
        with open(f'{bp.config_folder}/config.yml', 'r') as f:
            config = yaml.load( f.read() )
        if not any( [ 'ebumeter' in x for x in config['jack_monitors'] ] ):
            print('(init/ebumeter) adding ebumeter for jack_monitors under config.yml')
            config['jack_monitors'].append( 'ebumeter:in.L ebumeter:in.R' )
            with open(f'{bp.config_folder}/config.yml', 'w') as f:
                yaml.dump( config, f )

    check_config()
    
    Popen( 'ebumeter'.split() )

def stop():
    Popen( 'pkill ebumeter'.split() )

    
if sys.argv[1:]:
    try:
        option = {
            'start' : start,
            'stop'  : stop
            }[ sys.argv[1] ]()
    except:
        print( '(init/ebumeter) bad option' )
else:
    print(__doc__)
