#!/usr/bin/env python3

"""
    Runs 'jackminimix' on JACK inserted after pre.dic output:
    
    predic:out     --------\\
                            \\
    analog         --------( + )----> sound_card
                            /
    someJackClient --------/


    Usage:    jackminimix.py   start | stop


    Notice: jack sources to mixer inputs can be configured inside:
    
        pre.di.c/clients/bin/jackminimix_start.sh
"""

import sys
from subprocess import Popen

import basepaths as bp

def start():
    cmd = f'{bp.main_folder}/clients/bin/jackminimix_start.sh -i'
    Popen( cmd.split() )

def stop():
    Popen( 'pkill -f jackminimix'.split() )
    sys.exit()

if __name__ == '__main__':

    if sys.argv[1:]:
        option = sys.argv[1]
        if option == 'start':
            start()
        elif option == 'stop':
            stop()
        else:
            print(__doc__)
    else:
        print(__doc__)
