#!/usr/bin/env python3

"""
    A mouse volume control daemon

    use:   mouse_volume   start | stop
"""

import sys
from subprocess import Popen

import mouse_volume_daemon as mvd

def start():
    mvd.main_loop()

def stop():
    Popen( ['pkill', '-f',  'mouse_volume.py'] )

if sys.argv[1:]:

    try:
        option = {
            'start' : start,
            'stop'  : stop
            }[ sys.argv[1] ]()
    except:
        print( '(init/mouse_volume_daemon) bad option' )
else:
    print(__doc__)
