#!/usr/bin/env python3
"""
    Launchs shairport-sync: an Airplay audio player
    https://github.com/mikebrady/shairport-sync

    use:    pre.di.c/init/shairport-sync   start | stop
"""

import sys
from subprocess import Popen
from socket import gethostname

OUTPUT = 'pa' # 'alsa' or 'pa' (pulseaudio)

def start():

    cmd =  f'/usr/bin/shairport-sync --name {gethostname()} --output {OUTPUT}'
    Popen( cmd.split() )

def stop():
    Popen( 'pkill -f shairport-sync'.split() )

if sys.argv[1:]:
    try:
        option = {
            'start' : start,
            'stop'  : stop
            }[ sys.argv[1] ]()
    except:
        print( '(init/shairport-sync) bad option' )
else:
    print(__doc__)
