#!/usr/bin/env python3

"""
    Launch the spotify_monitor.py daemon that will:
    
    - listen for events from Spotify Desktop

    - and writes down the metadata into a file for others to read it.

    usage:   spotify_monitor   start | stop
"""

import sys
from subprocess import Popen
import basepaths as bp


def start():
    ###################### NOTICE #######################
    # For playerctl v1.x please use spotify_monitor_v1.py
    # For playerctl v2.x please use spotify_monitor_v2.py
    #####################################################
    Popen( f'{bp.main_folder}/clients/bin/spotify_monitor_v1.py' )

def stop():
    Popen( ['pkill', '-f',  'spotify_monitor'] )

if sys.argv[1:]:

    try:
        option = {
            'start' : start,
            'stop'  : stop
            }[ sys.argv[1] ]()
    except:
        print( '(init/spotify_monitor) bad option' )
else:
    print(__doc__)
