# used from scripts/iRadio.py

1:
    name:   rne
    url:    http://rtve-mp3-radiolive.flumotion.com/rtve/rtve-rne.mp3.m3u

2:
    name:   radioclasica 
    url :    http://rtve-mp3-radiolive.flumotion.com/rtve/rtve-radioclasica.mp3.m3u

3: 
    name:   radio3
    url:    http://rtve-mp3-radiolive.flumotion.com/rtve/rtve-radio3.mp3.m3u

4:
    name:   m80          
    url:    http://playerservices.streamtheworld.com/api/livestream-redirect/M80RADIO_SC

5:
    name:   los40        
    url:    http://19073.live.streamtheworld.com:3690/LOS40AAC_SC

6:
    name:   europafm     
    url:    http://212.129.60.86:9968/stream/1/

